#
# Requires that you already have a version running in production. Based on the
# _TRAFFIC_PERCENTAGE value defined in our build trigger, we will perform a
# canary release to that percentage of traffic to the service.
#

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -ex
        gcloud container images add-tag \
          ${_ARTIFACT_REGISTRY}/${REPO_NAME}:stage-${SHORT_SHA} \
          ${_ARTIFACT_REGISTRY}/${REPO_NAME}:${TAG_NAME} \

  #- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #  entrypoint: /bin/sh
  #  args:
  #    - "-c"
  #    - |
  #      set -ex
  #      gcloud --project ${_PRD_PROJECT_ID} \
  #        run deploy ${REPO_NAME} \
  #        --image ${_ARTIFACT_REGISTRY}/${REPO_NAME}:${TAG_NAME} \
  #        --region ${_DEFAULT_REGION} \
  #        --platform managed \
  #        --service-account project-service-account@${_PRD_PROJECT_ID}.iam.gserviceaccount.com \
  #        --no-traffic \
  #        --allow-unauthenticated

  #- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #  entrypoint: /bin/sh
  #  args:
  #    - "-c"
  #    - |
  #      set -ex
  #      gcloud --project ${_PRD_PROJECT_ID} \
  #        run services update-traffic ${REPO_NAME} \
  #        --region ${_DEFAULT_REGION} \
  #        --platform managed \
  #        --service-account project-service-account@${_PRD_PROJECT_ID}.iam.gserviceaccount.com \
  #        --to-revisions LATEST=${_TRAFFIC_PERCENTAGE} \
  #        --memory 512Mi \
  #        --vpc-connector ${_CONNECTOR_NAME} \
  #        --set-cloudsql-instances ${_CLOUD_MYSQL} \
  #        --update-env-vars MYSQL_CONN=${_CLOUD_MYSQL} \
  #        --update-env-vars MYSQL_DB=petclinic \
  #        --update-env-vars MYSQL_USER=app \
  #        --update-env-vars MYSQL_PASS=PaSsWoRd \

# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _POLICY_REPO: '' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator

# Cloud Build Timeout
timeout: 3600s
